# -*- coding: utf-8 -*-
"""modern_methods.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152IdpiYPxw-6U7SN0j9f1YDa22lslvs0
"""

import os
import time
import json
import pandas as pd
from openai import OpenAI
import re # Import the re module

# print("測試 ai_classify 函數:")
# for text in test_texts:
#     classification_result = ai_classify(text)
#     print(f"\n文本: {text}")
#     print(f"分類結果: {json.dumps(classification_result, ensure_ascii=False, indent=2)}")

from google.colab import userdata
userdata.get('OpenAI')

# 使用環境變數讀取 API Key

# Get the API key from Colab's secrets using the already imported 'userdata'
openai_api_key = userdata.get('OpenAI')

# Set the environment variable 'OPENAI_API_KEY'
os.environ['OPENAI_API_KEY'] = openai_api_key

client = OpenAI(
    api_key=os.environ.get("OPENAI_API_KEY"), # This will now correctly get the key
    timeout=30.0, # 設定超時時間
    max_retries=3 # 自動重試
)
MODEL_NAME = "gpt-4o"

documents = [
    "人工智慧正在改變世界,機器學習是其核心技術",
    "深度學習推動了人工智慧的發展,特別是在圖像識別領域",
    "今天天氣很好,適合出去運動",
    "機器學習和深度學習都是人工智慧的重要分支",
    "運動有益健康,每天都應該保持運動習慣"
]
text1 = "人工智慧正在改變世界,機器學習是其核心技術"
text2 = "機器學習和深度學習都是人工智慧的重要分支"
text3 = "今天的氣溫很舒適,適合戶外活動"
text4 = "區塊鏈技術的應用正在各行業快速擴展"
text5 = "運動有益健康,每天都應該保持運動習慣"

test_texts = [
  "這家餐廳的牛肉麵真的太好吃了,湯頭濃郁,麵條Q彈,下次一定再來!",
  "最新的AI技術突破讓人驚艷,深度學習模型的表現越來越好",
  "這部電影劇情空洞,演技糟糕,完全是浪費時間",
  "每天慢跑5公里,配合適當的重訓,體能進步很多"
]

article = """
人工智慧(AI)的發展正在深刻改變我們的生活方式。從早上起床時的智慧鬧鐘,
到通勤時的路線規劃,再到工作中的各種輔助工具,AI無處不在。

在醫療領域,AI協助醫生進行疾病診斷,提高了診斷的准確率和效率。透過分析
大量的醫療影像和病歷資料,AI能夠發現人眼容易忽略的細節,為患者提供更好
的治療方案。

教育方面,AI個人化學習系統能夠根據每個學生的學習進度和特點,提供客製化
的教學內容。這種因材施教的方式,讓學習變得更加高效和有趣。

然而,AI的快速發展也帶來了一些挑戰。首先是就業問題,許多傳統工作可能會
被AI取代。其次是隱私和安全問題,AI系統需要大量數據來訓練,如何保護個人
隱私成為重要議題。最後是倫理問題,AI的决策過程往往缺乏透明度,可能會產
生偏見或歧視。

面對這些挑戰,我們需要在推動AI發展的同時,建立相應的法律法規和倫理準則。
只有這樣,才能確保AI技術真正為人類福祉服務,創造一個更美好的未來。
"""

"""### --- B-1: 語意相似度計算 (10分) ---"""

def call_openai_api(prompt, max_tokens, temperature):
    try:
        response = client.chat.completions.create(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": "你是一個精確的文本分析助理。"},
                {"role": "user", "content": prompt}
            ],
            max_tokens=max_tokens,
            temperature=temperature
        )
        return response.choices[0].message.content
    except Exception as e:
        print(f"OpenAI API 呼叫錯誤: {e}")
        return ""

def ai_similarity(text1, text2):
    """
    使用 GPT-4o 判斷語意相似度
    要求:
    1. 設計適當的 prompt
    2. 返回 0-100 的相似度分數
    3. 處理 API 錯誤 (client 已內建重試)
    """
    prompt = f"""
請評估以下兩段文字的語意相似度。
考慮因素:
1. 主題相關性
2. 語意重疊程度
3. 表達的觀點是否一致

文字1: {text1}
文字2: {text2}

請只回答一個 0-100 的數字, 代表相似度百分比。
"""
    # 呼叫 API，要求 max_tokens=10 以獲得單個數字
    response_text = call_openai_api(prompt, max_tokens=10, temperature=0.0)

    # 處理結果
    try:
        # 嘗試從回應中提取數字
        score = int(re.search(r'\d+', response_text).group())
        return min(max(0, score), 100) # 確保分數在 0-100 之間
    except (ValueError, AttributeError):
        print(f"API 回應格式錯誤: {response_text}")
        return 0

# Test with highly similar texts
similarity_score_1 = ai_similarity(text1, text2)
print(f"Similarity between text1 and text2: {similarity_score_1}")
# Test with less similar texts
similarity_score_2 = ai_similarity(text3, text4)
print(f"Similarity between text3 and text4: {similarity_score_2}")

# Test with highly similar texts
similarity_score_1 = ai_similarity(text1, text2)
print(f"Similarity between text1 and text2: {similarity_score_1}")

# Test with less similar texts
text3 = "今天的氣溫很舒適,適合戶外活動"
text4 = "區塊鏈技術的應用正在各行業快速擴展"
similarity_score_2 = ai_similarity(text3, text4)
print(f"Similarity between text3 and text4: {similarity_score_2}")

"""### --- B-2: AI 文本分類 (10分) ---"""

def ai_classify(text):
    """
    使用 GPT-4o 進行多維度分類
    返回格式:
    {
        "sentiment":"正面/負面/中性",
        "topic":"主題類別 (例如: 科技, 運動, 美食, 旅遊, 其他)",
        "confidence": 0.95
    }
    """
    prompt = f"""
請分析以下這段文字, 執行多維度分類。
文本: "{text}"

請提供以下 JSON 格式的輸出:
{{
    "sentiment": "正面、負面或中性",
    "topic": "從 [科技, 運動, 美食, 旅遊, 其他] 中選擇一個最相關的主題",
    "confidence": "你對這次分類的信心指數 (0.0 到 1.0)"
}}
"""
    try:
        response = client.chat.completions.create(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": "你是一個精確的文本分析助理，並總是輸出JSON格式。"},
                {"role": "user", "content": prompt}
            ],
            response_format={"type": "json_object"},
            temperature=0.0 # 為了分類準確性，降低溫度
        )
        return json.loads(response.choices[0].message.content)
    except Exception as e:
        print(f"OpenAI API 呼叫錯誤: {e}")
        return {"sentiment": "錯誤", "topic": "錯誤", "confidence": 0.0}

"""### --- B-3: AI 自動摘要 (10分) ---"""

def ai_summarize(text, max_length):
    """
    使用 GPT-4o 生成摘要
    要求:
    1. 可控制摘要長度 (約 {max_length} 字)
    2. 保留關鍵資訊
    3. 語句通順
    """
    prompt = f"""
請將以下文章濃縮成一段通順且保留關鍵資訊的摘要。
摘要的長度請控制在 {max_length} 字左右。

文章:
{text}

摘要:
"""
    try:
        response = client.chat.completions.create(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": "你是一個精確的文本摘要助理。"},
                {"role": "user", "content": prompt}
            ],
            max_tokens=int(max_length * 1.5), # 給予模型足夠的空間生成摘要，但仍有一定限制
            temperature=0.7 # 稍高溫度增加創造性
        )
        return response.choices[0].message.content
    except Exception as e:
        print(f"OpenAI API 呼叫錯誤: {e}")
        return ""

summarized_text = ai_summarize(article, 100)
print(f"原始文章長度: {len(article)} 字")
print(f"摘要文章長度: {len(summarized_text)} 字")
print("\n摘要內容:")
print(summarized_text)